[build]
    functions = "functions"

[dev]
  publish = "client/myLibrary.html"


  [[headers]]
  for = "/*"
    [headers.values]
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
